### ISSUE TITLE
Feature request: Add a turbo button

### ISSUE THREAD

**Issue by petrpavlik** [DominikBucher12/XTouchBar#1]
That doesn't do anything, but pressing it makes me feel like it's compiling faster.

**Comment by DominikBucher12** [comment]
Added in https://github.com/DominikBucher12/XTouchBar/commit/c9d1d5db785ebe18457c876c928b20f6785dbbae 

We ship fast and cheap, you know the equation :D

Wait for release in few hours. Meanwhile, you can try to build the thing as a project, but keep in mind you need to re-enable the accessibility for this app while running it from Xcode vs the binary (some macOS magic probably.)

**Comment by DominikBucher12** [comment]
Ready in production. 🚀
